RANGE_NAME: "upgrade-22-to-23"
LME_BRANCH: "snl-ludus-test-framework"
LME_BRANCH_COMMIT: "a9952a1"
LME_VERSION: "2.3.0"
LME_REPO_URL: "/home/mreeve/vibe-home/LME"
SSH_USER: "localuser"
SSH_PASS: "password"
NOTES: "Deploy main 2.2.0, upgrade to snl-ludus-test-framework"
UPGRADE_FROM_BRANCH: "main"
UPGRADE_FROM_COMMIT: ""
UPGRADE_FROM_VERSION: "2.2.0"
