# {{ RANGE_NAME }}: LME {{ LME_VERSION }} — Auto-generated from params.yml
# yaml-language-server: $schema=https://docs.ludus.cloud/schemas/range-config.json
#
# Generated by: bash scripts/generate-range.sh ranges/{{ RANGE_NAME }}
# No hardcoded credentials — ludus_lme_agents auto-resolves from ludus_lme_server.

ludus:
  - vm_name: "{{ range_id }}-lme-server"
    hostname: "lme-server"
    template: ubuntu-24.04-x64-server-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 32
    cpus: 4
    linux: true
    roles:
      - ludus_lme_server
    role_vars:
      ludus_lme_server_version: "{{ LME_VERSION }}"
      ludus_lme_server_git_ref: "{{ GIT_REF }}"
      ludus_lme_server_repo_url: "{{ REPO_URL }}"
{{ OFFLINE_ROLE_VAR }}
  - vm_name: "{{ range_id }}-win11-endpoint"
    hostname: "WIN11-EP"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 30
    ram_gb: 8
    cpus: 2
    windows:
      sysprep: false
    roles:
      - name: ludus_lme_agents
        depends_on:
          - vm_name: "{{ range_id }}-lme-server"
            role: ludus_lme_server

  - vm_name: "{{ range_id }}-ubuntu-endpoint"
    hostname: "ubuntu-ep"
    template: ubuntu-24.04-x64-server-template
    vlan: 10
    ip_last_octet: 40
    ram_gb: 4
    cpus: 2
    linux: true
    roles:
      - name: ludus_lme_agents
        depends_on:
          - vm_name: "{{ range_id }}-lme-server"
            role: ludus_lme_server
