run_every:
  minutes: 1

buffer_time:
  minutes: 15

writeback_index: elastalert_status

alert_time_limit:
  days: 2

es_host: lme-elasticsearch
es_port: 9200
use_ssl: true
verify_certs: false

#exists in the container
rules_folder: /opt/elastalert/rules
