RANGE_NAME: "offline-23"
LME_IP: "10.3.10.10"
CALDERA_IP: ""
OFFLINE_IP: "10.3.10.10"
LME_BRANCH: "develop"
LME_BRANCH_COMMIT: "1927608e17bb620031aba17001a524d81ef591a0"
LME_VERSION: "2.3.0"
SSH_USER: "localuser"
SSH_PASS: "password"
ELASTIC_PASS: ""
NOTES: "Air-gapped LME 2.3 — Ludus testing mode, DNS blocked"
