on:
  workflow_dispatch: 
    inputs:
      version:
        description: "Release version (e.g., 1.1.0)"
        required: true
        type: string

name: Build Release

jobs: 
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date 
        id: date
        run: | 
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build Assets
        run: git ls-files | zip LME-${{ inputs.version }}.zip -@

      - name: Create Draft Release 
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: LME v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          body: | 
            ## [${{ inputs.version }}] - Timberrrrr! - ${{ env.date }}
            ${{ steps.release.outputs.changelog }}
          files: LME-${{ inputs.version }}.zip
          draft: true
          prerelease: false
          discussion_category_name: "Announcements"
          generate_release_notes: true
          fail_on_unmatched_files: true
